# Generated by Django 4.1.7 on 2023-03-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_alter_wishlist_product'),
    ]

    operations = [
        migrations.DeleteModel(
            name='wishlist',
        ),
    ]
