# Generated by Django 4.1.7 on 2023-03-24 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_address_city_alter_userprofile_district'),
        ('product', '0009_alter_wishlist_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wishlist',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.productvarient'),
        ),
    ]
