# Generated by Django 4.1.7 on 2023-04-05 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_coupon_order_usercoupon_payment_orderproduct_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ip',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_id',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='refund_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
