# Generated by Django 4.1.7 on 2023-04-07 04:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_remove_order_ip_alter_payment_payment_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
