# Generated by Django 4.1.7 on 2023-04-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_payment_razorpay_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='used_coupon',
            field=models.CharField(blank=True, default='empty', max_length=100),
        ),
    ]
