# Generated by Django 4.1.7 on 2023-04-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_remove_payment_used_coupon_order_used_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='is_shipping',
            field=models.BooleanField(default=False),
        ),
    ]
