# Generated by Django 4.1.7 on 2023-03-13 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Madurai', 'Madurai'), ('Hydrabad', 'Hydrabad'), ('Banglore', 'Banglore'), ('Ernakulam', 'Ernakulam'), ('Coimbator', 'Coimbator'), ('Kannur', 'Kannur'), ('Kozhikkode', 'Kozhikkode'), ('Hubli', 'Hubli'), ('Thiruvananthapuram', 'Thiruvananthapuram')], max_length=20, null=True),
        ),
    ]
