# Generated by Django 4.1.7 on 2023-03-22 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVarient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('color', models.CharField(max_length=50, unique=True)),
                ('price', models.PositiveBigIntegerField(null=True)),
                ('offer', models.PositiveIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Size', models.CharField(max_length=10, null=True)),
                ('stock', models.PositiveIntegerField(null=True)),
                ('varient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.productvarient')),
            ],
        ),
        migrations.RemoveField(
            model_name='product',
            name='color',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='product',
            name='stock',
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='product',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Madurai', 'Madurai'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hydrabad', 'Hydrabad'), ('Coimbator', 'Coimbator'), ('Hubli', 'Hubli'), ('Kozhikkode', 'Kozhikkode'), ('Banglore', 'Banglore'), ('Ernakulam', 'Ernakulam')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Madurai', 'Madurai'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hydrabad', 'Hydrabad'), ('Coimbator', 'Coimbator'), ('Hubli', 'Hubli'), ('Kozhikkode', 'Kozhikkode'), ('Banglore', 'Banglore'), ('Ernakulam', 'Ernakulam')], max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='Color',
        ),
        migrations.AddField(
            model_name='productvarient',
            name='Product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.product'),
        ),
        migrations.AddField(
            model_name='productimage',
            name='varient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user.productvarient'),
        ),
    ]
