# Generated by Django 4.1.7 on 2023-03-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_productvarient_size_remove_product_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Madurai', 'Madurai'), ('Banglore', 'Banglore'), ('Ernakulam', 'Ernakulam'), ('Kozhikkode', 'Kozhikkode'), ('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Coimbator', 'Coimbator')], max_length=255),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='color',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Green', 'Green'), ('Red', 'Red'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Orange', 'Orange')], max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='offer',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='Size',
            field=models.CharField(choices=[('XS', 'XS'), ('S', 'S'), ('M', 'M'), ('L', 'L'), ('XL', 'XL'), ('XXL', 'XXL'), ('XXXL', 'XXXL'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('28', '28'), ('30', '30'), ('32', '32'), ('34', '34'), ('36', '36'), ('38', '38'), ('40', '40'), ('42', '42'), ('UNI', 'UNI')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='size',
            name='stock',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Madurai', 'Madurai'), ('Banglore', 'Banglore'), ('Ernakulam', 'Ernakulam'), ('Kozhikkode', 'Kozhikkode'), ('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Coimbator', 'Coimbator')], max_length=20, null=True),
        ),
    ]
