# Generated by Django 4.1.7 on 2023-03-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_alter_address_city_alter_productvarient_color_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hydrabad', 'Hydrabad'), ('Ernakulam', 'Ernakulam'), ('Kannur', 'Kannur'), ('Banglore', 'Banglore'), ('Hubli', 'Hubli'), ('Kozhikkode', 'Kozhikkode'), ('Coimbator', 'Coimbator'), ('Madurai', 'Madurai')], max_length=255),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='offer',
            field=models.PositiveIntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hydrabad', 'Hydrabad'), ('Ernakulam', 'Ernakulam'), ('Kannur', 'Kannur'), ('Banglore', 'Banglore'), ('Hubli', 'Hubli'), ('Kozhikkode', 'Kozhikkode'), ('Coimbator', 'Coimbator'), ('Madurai', 'Madurai')], max_length=20, null=True),
        ),
    ]
