# Generated by Django 4.1.7 on 2023-03-24 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_address_city_alter_productvarient_offer_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Kannur', 'Kannur'), ('Madurai', 'Madurai'), ('Hubli', 'Hubli'), ('Ernakulam', 'Ernakulam'), ('Hydrabad', 'Hydrabad'), ('Banglore', 'Banglore'), ('Coimbator', 'Coimbator'), ('Kozhikkode', 'Kozhikkode'), ('Thiruvananthapuram', 'Thiruvananthapuram')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Kannur', 'Kannur'), ('Madurai', 'Madurai'), ('Hubli', 'Hubli'), ('Ernakulam', 'Ernakulam'), ('Hydrabad', 'Hydrabad'), ('Banglore', 'Banglore'), ('Coimbator', 'Coimbator'), ('Kozhikkode', 'Kozhikkode'), ('Thiruvananthapuram', 'Thiruvananthapuram')], max_length=20, null=True),
        ),
    ]
