# Generated by Django 4.1.7 on 2023-03-24 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.RenameField(
            model_name='size',
            old_name='Size',
            new_name='size',
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Madurai', 'Madurai'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Banglore', 'Banglore'), ('Ernakulam', 'Ernakulam'), ('Coimbator', 'Coimbator'), ('Kozhikkode', 'Kozhikkode')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Madurai', 'Madurai'), ('Kannur', 'Kannur'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Banglore', 'Banglore'), ('Ernakulam', 'Ernakulam'), ('Coimbator', 'Coimbator'), ('Kozhikkode', 'Kozhikkode')], max_length=20, null=True),
        ),
    ]
