# Generated by Django 4.1.7 on 2023-03-26 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Kozhikkode', 'Kozhikkode'), ('Hydrabad', 'Hydrabad'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Madurai', 'Madurai'), ('Coimbator', 'Coimbator'), ('Hubli', 'Hubli'), ('Ernakulam', 'Ernakulam'), ('Kannur', 'Kannur'), ('Banglore', 'Banglore')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Kozhikkode', 'Kozhikkode'), ('Hydrabad', 'Hydrabad'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Madurai', 'Madurai'), ('Coimbator', 'Coimbator'), ('Hubli', 'Hubli'), ('Ernakulam', 'Ernakulam'), ('Kannur', 'Kannur'), ('Banglore', 'Banglore')], max_length=20, null=True),
        ),
    ]
