# Generated by Django 4.1.7 on 2023-04-09 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Ernakulam', 'Ernakulam'), ('Banglore', 'Banglore'), ('Coimbator', 'Coimbator'), ('Madurai', 'Madurai'), ('Hubli', 'Hubli'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kannur', 'Kannur'), ('Hydrabad', 'Hydrabad'), ('Kozhikkode', 'Kozhikkode')], max_length=255),
        ),
        migrations.AlterField(
            model_name='productvarient',
            name='color',
            field=models.CharField(choices=[('White', 'White'), ('Black', 'Black'), ('Green', 'Green'), ('Red', 'Red'), ('Yellow', 'Yellow'), ('Blue', 'Blue'), ('Brown', 'Brown'), ('Orange', 'Orange')], max_length=50),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Ernakulam', 'Ernakulam'), ('Banglore', 'Banglore'), ('Coimbator', 'Coimbator'), ('Madurai', 'Madurai'), ('Hubli', 'Hubli'), ('Thiruvananthapuram', 'Thiruvananthapuram'), ('Kannur', 'Kannur'), ('Hydrabad', 'Hydrabad'), ('Kozhikkode', 'Kozhikkode')], max_length=20, null=True),
        ),
    ]
