# Generated by Django 4.1.7 on 2023-04-12 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_address_city_alter_userprofile_district'),
    ]

    operations = [
        migrations.AlterField(
            model_name='address',
            name='city',
            field=models.CharField(choices=[('Kannur', 'Kannur'), ('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Kozhikkode', 'Kozhikkode'), ('Banglore', 'Banglore'), ('Ernakulam', 'Ernakulam'), ('Coimbator', 'Coimbator'), ('Madurai', 'Madurai'), ('Thiruvananthapuram', 'Thiruvananthapuram')], max_length=255),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='district',
            field=models.CharField(blank=True, choices=[('Kannur', 'Kannur'), ('Hydrabad', 'Hydrabad'), ('Hubli', 'Hubli'), ('Kozhikkode', 'Kozhikkode'), ('Banglore', 'Banglore'), ('Ernakulam', 'Ernakulam'), ('Coimbator', 'Coimbator'), ('Madurai', 'Madurai'), ('Thiruvananthapuram', 'Thiruvananthapuram')], max_length=20, null=True),
        ),
    ]
